<?php
$lang = $this->model('lang');
$lower_cat_label = strtolower($lang['cat.label']);


$category = $this->category;


$this->layout()->appendSection('layout.head', <<<EndJS
<script type="text/javascript">

	$(document).ready(function() {

		cpv_trigger = $("input#cpv_trigger");
		cpv_target = $("#cpv_target");

		$('#cpv_target input:checkbox').live('click', function() {
			cpvChangeSelection($(this).val(), $(this).prop('checked'));
		});

		$('#cpv_listall input:checkbox').live('click', function() {
			cpvChangeSelection($(this).val(), $(this).prop('checked'));
		});

		cpvLookup();

		var del_button = $('<input type="submit" name="submitdelete" value="Delete {$lang['cat.label.plural']}" />');
		del_button.click(function () {
			return confirm('Please confirm that you want to delete this {$lower_cat_label}.\\n\\nAny Items associated with this category will remain, but no longer be registered with it.\\n\\nThis operation cannot be undone.');
		});
		$('#delete_button_container').append(del_button);

	});

</script>
EndJS
);
?>

<?php
Ecl_Helper_Html::form('categoryform', $this->router()->makeAbsoluteUri('/admin/categories/edit/?id='. $this->category->id) );
Ecl_Helper_Html::formHidden('session_key', $this->model('user')->getSessionKey());
?>


<input type="submit" name="submitsave0" value="Save Changes" style="position: absolute; left: -100%;" />


<div id="delete_button_container"></div>


<h1>Edit <?php $this->out($lang['cat.label']); ?> : <?php $this->out($this->category->name); ?></h1>
<p><?php $this->out($lang['cat.label.plural']); ?> are used to group together items of equipment with a similar purpose or functionality.</p>


<?php
$this->render('categories_snippets_editsubform');
?>

<div style="margin: 1em 0 2em 0;">
	<?php
	Ecl_Helper_Html::formSubmit('submitcancel', 'Cancel');
	Ecl_Helper_Html::formSubmit('submitsave', 'Save Changes');
	?>
</div>


<h3>Items Listed</h3>
<?php
if (0 < $category->item_count_internal) {
	?>
	<p>This <?php $this->out(strtolower($lang['cat.label'])); ?> contains <em><?php $this->out($category->item_count_internal); ?> item<?php echo ((1 < $category->item_count_internal) ? 's' : ''); ?></em> of equipment.</p>

	<p><a href="<?php echo $this->router()->makeAbsoluteUri("/browse/category-{$category->id}-".urlencode($category->name)); ?>">View items in catalogue</a></p>

	<p>If you would like to transfer your items to a different <?php $this->out(strtolower($lang['cat.label'])); ?>, please select a destination to transfer all items to.</p>
	<?php
	$options = array('' => '') + $this->model('categorystore')->findAll()->toAssoc('id', 'name');
	unset($options[$category->id]);

	Ecl_Helper_Html::formSelect('destination', $options);
	?>
	<br /><br />
	<?php
	$cboxes = array();
	$cboxes[] = array (
		'name'      => 'delete_on_transfer' ,
		'id'        => 'delete_on_transfer' ,
		'label'     => 'Delete current '. strtolower($lang['cat.label']).' after transfer' ,
		'value'     => '1' ,
		'selected'  => false ,
	);
	Ecl_Helper_Html::formCheckboxTable($cboxes);
	?>
	<div>
		<?php Ecl_Helper_Html::formSubmit('submittransfer', 'Transfer Items'); ?>
	</div>
	<?php
} else {
	?>
	<p>This <?php $this->out(strtolower($lang['cat.label'])); ?> is not associated with any items.</p>
	<?php
}
?>


<?php
Ecl_Helper_Html::formClose();
?>


