

<h1>Administer Categories</h1>


<p>Below is the list of the categories available for use in this catalogue.</p>
<p>Categories are used to group together items of equipment with a similar purpose or functionality.</p>


<div class="grid_row">

	<div class="grid_8col">

		<?php
		if ($this->categories->count()==0) {
			?>
			<p class="warning">No categories have been setup yet.</p>
			<?php
		} else {
			?>
			<ul>
				<?php
				$url = $this->router()->makeAbsoluteUri('/admin/categories/edit/?id=');
				foreach($this->categories as $i => $category) {
					?>
					<li><a href="<?php $this->out($url . $category->id); ?>"><?php $this->out($category->name); ?> <span class="count">(<?php $this->out($category->getItemCount()); ?>)</span></a></li>
					<?php
				}
				?>
			</ul>
			<?php
		}
		?>

	</div>

	<div class="grid_4col grid_last">

		<div class="boxed">
			<p class="title">Add a New Category</p>
			<?php Ecl_Helper_Html::form('createcategoryform', $this->router()->makeAbsoluteUri('/admin/categories/create/') ); ?>
			<dl>
				<dt><?php Ecl_Helper_Html::formLabel('name', 'Name'); ?></dt>
				<dd><?php Ecl_Helper_Html::formInput('name', 20, 250); ?></dd>
			</dl>
			<div style="text-align: right;">
				<?php
				Ecl_Helper_Html::formSubmit('submitadd', 'Next &gt;');
				?>
			</div>
			<?php Ecl_Helper_Html::formClose(); ?>
		</div>

		<div class="boxed" style="margin-top: 1em;">
			<p class="title">Rebuild Category Item Counts</p>
			<p>If you need to manually rebuild the item counts cached for each category, use the button below.</p>
			<div style="text-align: right;">
				<?php
				Ecl_Helper_Html::form('rebuildcountsform', $this->router()->makeAbsoluteUri('/admin/categories/rebuildcounts/') );
				Ecl_Helper_Html::formSubmit('submitrebuild', 'Rebuild Item Counts');
				Ecl_Helper_Html::formClose();
				?>
			</div>
		</div>

		<div class="boxed" style="margin-top: 1em;">
			<p class="title">Configure CPV Codes</p>
			<p>The full CPV list contains almost 9,500 entries and can slow down the category administration pages.</p>
			<p>You can configure Kit-Catalogue to only use the CPV codes you find relevant by using the button below.</p>
			<div style="text-align: right;">
				<?php
				Ecl_Helper_Html::form('rebuildcountsform', $this->router()->makeAbsoluteUri('/admin/categories/cpvcodes') );
				Ecl_Helper_Html::formSubmit('submitcpvcodes', 'Configure CPV Codes');
				Ecl_Helper_Html::formClose();
				?>
			</div>
		</div>

	</div>

</div>


