<?php
if ($this->model('security')->checkAuth(KC__AUTH_CANADMIN)) {
	$edit_url = $this->router()->makeAbsoluteUri('/admin/items/edit/new');
	$back_url = base64_encode($this->request()->relativeUri());
	$editlink = sprintf('&nbsp;<a class="admin_link" href="%1$s?backlink=%2$s">add an item &raquo;</a>', $edit_url, $back_url);
} else {
	$editlink = '';
}


$this->layout()->appendSection('layout.head', '
<style type="text/css">

	ul#atoz { list-style: none; margin: 0; padding: 0; }
	ul#atoz li { float: left; margin: 0 0 0 3px; padding: 0; }

	ul#atoz li a,
	ul#atoz li span { min-width: 1.3em; display: block; padding: 0.4em; text-align: center; }

	ul#atoz li a { background-color: #D4EDB5; font-weight: bold; }
	zul#atoz li span { background-color: #f6f6f6; border: 1px solid #dd9; color: #999; font-weight: bold; }

	ul#atoz li.active span { padding-bottom: 8px; border: 1px solid #ddd; border-bottom: 0; background-color: #fff !important; }

	ul#atoz li.noitems span { background-color: #eee; color: #aaa; font-weight: normal; }

</style>
');

?>

<h1>Items A-Z</h1>
<p class="note">Equipment and facilities are available for manufacturers starting with the following letters</p>


<ul id="atoz" class="cf">
<?php
$full_alphabet = range('A', 'Z');
$full_alphabet[] = 'Other';


foreach($full_alphabet as $i => $letter) {
	if ($letter == $this->letter) {
		echo "<li class=\"active\"><span title=\"Currently selected\">{$letter}</span></li>";
	} else {
		if (in_array($letter, $this->alphabet)) {
			echo "<li><a href=\"./?letter={$letter}\">{$letter}</a></li>";
		} else {
			echo "<li class=\"noitems\"><span title=\"No items found\">{$letter}</span></li>";
		}
	}
}
?>
</ul>

<div style="height: 1em; z-index: -10; margin-top: -1px; padding-bottom: 1px; border-top: 1px solid #ddd;"></div>


<?php
if ($this->items->count()==0) {
	?>
	<p>There are no items of equipment or facilities listed, please try a different letter.</p>
	<?php
} else {
	?>
	<h2>Equipment and facilities listed under "<?php $this->out($this->letter); ?>".</h2>
	<ul id="item-list">
	<?php
	$url_stub = $this->router()->makeAbsoluteUri('/item/');
	foreach($this->items as $item) {
		$this->layout()->renderItemInList($item, "{$url_stub}{$item->url_suffix}");
	}
	?>
</ul><?php
}
?>
