<?php
$accesslevel = $this->accesslevel;


$this->layout()->addGlobalJavascript();

$this->layout()->appendSection('layout.head', <<<EndJS
<script type="text/javascript">

	$(document).ready(function() {

		var del_button = $('<input type="submit" name="submitdelete" value="Delete Access Level" />');
		del_button.click(function () {
			return confirm('Please confirm that you want to delete this access level.\\n\\nThis operation cannot be undone.');
		});
		$('#delete_button_container').append(del_button);

	});

</script>
EndJS
);
?>


<?php
Ecl_Helper_Html::form('accesslevelform', $this->request()->uri());
Ecl_Helper_Html::formHidden('session_key', $this->model('user')->getSessionKey());
?>


<h1>Edit Access Level: <?php $this->out($accesslevel->name); ?></h1>
<p>Here you can edit this access level.</p>


<input type="submit" name="submitsave" value="Save Changes" style="position: absolute; left: -100%;" />


<div id="delete_button_container"></div>


<dl class="form">
	<dt>Access Level Name</dt>
	<dd><?php Ecl_Helper_Html::formInput('name', 50, 250, $accesslevel->name); ?></dd>
</dl>

<div>
	<?php Ecl_Helper_Html::formSubmit('submitsave', 'Save Changes'); ?>
</div>




<?php
Ecl_Helper_Html::formClose();
?>


