<?php

$user = $this->model('user');

?>

<h1>Available Departments</h1>

<?php
if ($this->departments->count()==0) {
	if ($this->model('user')->isAnonymous()) {
		?>
		<p class="intro">There are no publically available department listed at present. You may have to <a href="<?php echo $this->router()->makeAbsoluteUri('/'); ?>">sign in</a> to browse this catalogue.</p>
		<?php
	} else {
		?>
		<p class="intro">There are no departments available, so it is likely this catalogue is empty.</p>
		<?php
	}
} else {
	?>
	<p class="intro">The following departments have equipment listed in this catalogue.</p>
	<ul class="mainmenu_ul">
		<?php
		foreach($this->departments as $i => $department) {
			?>
			<li><a href="<?php echo $this->router()->makeAbsoluteUri("/department/{$department->url_suffix}"); ?>"><?php $this->out($department->name); ?> <span class="count">(<?php $this->out($department->getItemCount($user->param('visibility'))); ?>)</span></a></li>
			<?php
		}
		?>
	</ul>
	<?php
}

?>
