<?php

$user = $this->model('user');
$lang = $this->model('lang');

?>

<h1><?php $this->out($lang['dept.label.plural']); ?></h1>

<?php
if ($this->departments->count()==0) {
	if ($this->model('user')->isAnonymous()) {
		?>
		<p class="note">There are no publically available <?php $this->out(strtolower($lang['dept.label.plural'])); ?> listed at present. You may have to <a href="<?php echo $this->router()->makeAbsoluteUri('/'); ?>">sign in</a> to browse this catalogue.</p>
		<?php
	} else {
		?>
		<p class="note">There are no <?php $this->out(strtolower($lang['dept.label.plural'])); ?> available so it is likely this catalogue is empty.</p>
		<?php
	}
}

if ($this->departments->count()>0) {

	if ($this->departments->count()>10) {
		$chunks = Ecl_Helper_Array::split($this->departments->toArray(), 2);
	} else {
		$chunks = array ( 0 => $this->departments );
	}
	?>
	<p class="note">The following <?php $this->out(strtolower($lang['dept.label.plural'])); ?> have equipment listed in this catalogue.</p>
	<div id="categories">
		<table class="layout" style="width: 900px; margin: 0 1em 0 1em;">
		<tr>
		<?php
		foreach($chunks as $chunk) {
			if (!empty($chunk)) {
				?>
				<td>
					<ul>
						<?php
						foreach($chunk as $i => $department) {
							?>
							<li><a href="<?php echo $this->router()->makeAbsoluteUri("/{$lang['dept.route']}/{$department->url_suffix}"); ?>"><?php $this->out($department->name); ?> <span class="count">(<?php $this->out($department->getItemCount($user->param('visibility'))); ?>)</span></a></li>
							<?php
						}
						?>
					</ul>
				</td>
				<?php
			}
		}
		?>
		</tr>
		</table>
	</div>
	<?php
}
?>
