<?php
$selected_category_id = (is_object($this->category)) ? $this->category->id : null ;

$this->layout()->appendSection('layout.head', '
<style type="text/css">

	ul.category_list li { font-weight: bold; }
	ul.category_list li a { font-weight: normal; }

</style>
');
?>
<h1><?php $this->out($this->department->name); ?></h1>

<?php
if (!$this->items) {
	?>
	<p class="intro">There are no items of equipment or facilities associated with this department and category.</p>
	<?php
} else {
	?>
	<p class="intro">The following equipment and facilities are listed under this department and category.</p>
	<?php
}



if ($this->model('security')->checkAuth(array(KC__AUTH_CANADMIN, KC__AUTH_CANEDIT) )) {
	?>
	<div style="float: right;">
		<?php
		$edit_url = $this->router()->makeAbsoluteUri('/admin/items/edit/new');
		$back_url = base64_encode($this->request()->relativeUri());
		printf('<div class="editlink"><a style="float: right;" class="admin_link" href="%1$s?backlink=%2$s">new item</a></div>', $edit_url, $back_url);
		?>
	</div>
	<?php
}
?>


<div class="grid_row">

	<div class="grid_4col grid_lastcol noprint">
		<h2 class="cat_title">Available Categories:</h2>
		<?php
		if (!$this->categories) {
			?>
			<p>No categories found for this department.</p>
			<?php
		} else {
			?>
			<ul class="category_list">
				<?php
				if ($selected_category_id === null) {
					printf('<li>%1$s</li>', 'Show All Items');
				} else {
					printf('<li><a href="%2$s">%1$s</a></li>', 'Show All Items', $this->router()->makeAbsoluteUri("/department/{$this->department->url_suffix}"));
				}

				$url_stub = $this->router()->makeAbsoluteUri("/department/{$this->department->url_suffix}/category/");
				foreach($this->categories as $category) {
					if ($selected_category_id == $category->id) {
						printf('<li class="current">%1$s</li>', $this->escape($category->name));
					} else {
						printf('<li><a href="%2$s">%1$s</a></li>', $this->escape($category->name), "{$url_stub}{$category->url_suffix}");
					}
				}
				?>
			</ul>
			<?php
		}
		?>
	</div>


	<div class="grid_8col">
		<?php
		if (is_object($this->category)) {
			printf('<h2 class="listtitle">Items in %s</h2>', $this->category->name);
		} else {
			printf('<h2 class="listtitle">All Items of Equipment</h2>');
		}

		if ($this->items) {
			?>
			<div class="item_list">
				<?php
				$url_stub = $this->router()->makeAbsoluteUri("/department/{$this->department->url_suffix}/item/");
				foreach($this->items as $item) {
					$this->layout()->renderItemInList($item, "{$url_stub}{$item->url_suffix}");
				}
				?>
			</div>
			<?php
		}
		?>
	</div>

</div>