<?php

$user = $this->model('user');
$lang = $this->model('lang');

?>

<h1><?php $this->out($lang['cat.label.plural']); ?></h1>

<?php
if ($this->categories->count()==0) {
	if ($this->model('user')->isAnonymous()) {
		?>
		<p class="note">There are no publically available <?php $this->out(strtolower($lang['cat.label.plural'])); ?> listed at present. You may have to <a href="<?php echo $this->router()->makeAbsoluteUri('/signin'); ?>">sign in</a> to browse this catalogue.</p>
		<?php
	} else {
		?>
		<p class="note">There are no <?php $this->out(strtolower($lang['cat.label.plural'])); ?> available so it is likely this catalogue is empty.</p>
		<?php
	}
}

if ($this->categories->count()>0) {

	if ($this->categories->count()>10) {
		$chunks = Ecl_Helper_Array::split($this->categories->toArray(), 2);
	} else {
		$chunks = array ( 0 => $this->categories );
	}
	?>
	<p class="note">The following is a list of all the <?php $this->out(strtolower($lang['cat.label.plural'])); ?> used in this catalogue.</p>

	<div id="categories">
		<table class="layout" style="width: 900px; margin: 1em auto;">
		<tr>
		<?php
		foreach($chunks as $chunk) {
			if (!empty($chunk)) {
				?>
				<td>
					<ul>
						<?php
						foreach($chunk as $i => $category) {
							if (false) {
								?>
								<li><a href="<?php echo $this->router()->makeAbsoluteUri("/{$lang['cat.route']}/{$category->slug}"); ?>"><?php $this->out($category->name); ?> <span class="count">(<?php $this->out($category->getItemCount($user->param('visibility'))); ?>)</span></a></li>
								<?php
							}
							?>
							<li><a href="<?php echo $this->router()->makeAbsoluteUri('/browse/'.strtolower($lang['cat.label'])."-{$category->id}-".urlencode($category->name)); ?>"><?php $this->out($category->name); ?> <span class="count">(<?php $this->out($category->getItemCount($user->param('visibility'))); ?>)</span></a></li>
							<?php
						}
						?>
					</ul>
				</td>
				<?php
			}
		}
		?>
		</tr>
		</table>
	</div>
	<?php
}?>
