<?php
$lang = $this->model('lang');


if ($this->model('security')->checkAuth(KC__AUTH_CANADMIN)) {
	$edit_url = $this->router()->makeAbsoluteUri('/admin/items/edit/new');
	$back_url = base64_encode($this->request()->relativeUri());
	printf('<a href="%1$s?backlink=%2$s">add an item &raquo;</a>', $edit_url, $back_url);
}
?>


<h1><?php $this->out($this->category->name); ?></h1>

<?php
if (0 == count($this->items)) {
	?>
	<p class="note">There are no items listed, please try a different <?php $this->out(strtolower($lang['cat.label'])); ?>.</p>
	<?php
} else {
	?>
	<p class="note">The following equipment and facilities are listed under this <?php $this->out(strtolower($lang['cat.label'])); ?>.</p>

	<ul id="item-list">
		<?php
		$url_stub = $this->router()->makeAbsoluteUri("/category/{$this->category->url_suffix}/item/");
		foreach($this->items as $item) {
			$this->layout()->renderItemInList($item, "{$url_stub}{$item->url_suffix}");
		}
		?>
	</ul>
	<?php
	}

?>
