<?php

$all_buildings = $this->model('buildingstore')->findAllUsed(KC__VISIBILITY_INTERNAL)->toAssoc('id', 'name');


$staff_contacts = $this->model('itemstore')->findAllContacts(KC__VISIBILITY_INTERNAL);
$staff_contacts = Ecl_Helper_Array::duplicateValueAsKey($staff_contacts);


$all_departments = $this->model('departmentstore')->findAll(KC__VISIBILITY_INTERNAL)->toAssoc('id', 'name');

$all_manufacturers = $this->model('itemstore')->findAllManufacturers(KC__VISIBILITY_INTERNAL);
$all_manufacturers = Ecl_Helper_Array::duplicateValueAsKey($all_manufacturers);


function submitbuttons() {
	echo('<div style="margin-top: 1em;">');
	Ecl_Helper_Html::formSubmit('viewreport', 'View');
	Ecl_Helper_Html::formSubmit('downloadreport', 'Download');
	echo('</div>');
}
?>


<h1 class="green-bar">Item Reports</h1>

<div class="white-box">
	<h4>Items by Building</h4>
	<p class="note">Show all the items of equipment listed within the given building.</p>
	<form action="./itemsbybuilding" method="get">
	<?php
		Ecl_Helper_Html::formSelect('building', $all_buildings);
		submitbuttons();
	?>
	</form>
</div>

<div class="white-box">
	<h4>Items by Department</h4>
	<p class="note">Show all the items of equipment associated with the given department.</p>
	<form action="./itemsbydept" method="get">
	<?php
		Ecl_Helper_Html::formSelect('department', $all_departments);
		submitbuttons();
	?>
	</form>
</div>

<div class="white-box">
	<h4>Items by Staff Contact</h4>
	<p class="note">Show all the items of equipment associated with the given staff contact.</p>

	<form action="./itemsbystaff" method="get">
	<?php
		Ecl_Helper_Html::formSelect('contact', $staff_contacts);
		submitbuttons();
	?>
	</form>
</div>

<div class="white-box">
	<h4>Items by Manufacturer</h4>
	<p class="note">Show all the items of equipment associated with the given manufacturer.</p>

	<form action="./itemsbymanufacturer" method="get">
	<?php
		Ecl_Helper_Html::formSelect('manufacturer', $all_manufacturers);
		submitbuttons();
	?>
	</form>
</div>


