<h1>Reports</h1>


<div class="dev_todo">
	<p>The reporting area is a little spartan at present, but we will be adding many more reports in future versions of Kit-Catalogue, so watch this space!</p>
</div>


<p>To view the reports available for the different aspects of your catalogue, please select from the list below.</p>

<ul>
	<li><a href="../items/">Items</a></li>
	<li><a href="../staffcontacts/">Staff Contacts</a></li>
</ul>


