<?php
$field = $this->field;


$this->router()->layout()->addBreadcrumb('Custom Fields', $this->router()->makeAbsoluteUri('/admin/customfields/index/'));
$this->router()->layout()->addBreadcrumb("Editing : {$field->name}", $this->router()->makeAbsoluteUri("/admin/customfields/edit/{$field->id}"));



$this->layout()->appendSection('layout.head', <<<EndJS
<script type="text/javascript">

	$(document).ready(function() {

		var del_button = $('<input type="submit" name="submitdelete" value="Delete Custom Field" />');
		del_button.click(function () {
			return confirm('Please confirm that you want to delete this custom field.\\n\\nAll item data for this field will be lost.\\n\\nThis operation cannot be undone.');
		});
		$('#delete_button_container').append(del_button);

	});

</script>
EndJS
);
?>


<?php
Ecl_Helper_Html::form('customfieldform', $this->request()->uri());
Ecl_Helper_Html::formHidden('session_key', $this->model('user')->getSessionKey());
?>


<input type="submit" name="submitsave" value="Save Changes" style="position: absolute; left: -100%;" />


<div id="delete_button_container"></div>


<h1>Edit Field: <?php $this->out($field->name); ?></h1>


<p>Here you can edit this field.</p>
<dl class="form">

<dt>Name</dt>
	<dd><?php Ecl_Helper_Html::formInput('name', 50, 250, $field->name); ?></dd>

</dl>

<div>
	<?php Ecl_Helper_Html::formSubmit('submitsave', 'Save Changes'); ?>
</div>


<?php
Ecl_Helper_Html::formClose();
?>


