<?php
$this->router()->layout(null);
$this->response()->setHeader('Content-Type', 'text/html');
?>
<html>
<head>
<style>

dt { float: left; clear: left; margin: 0 0.5em 0 0; font-weight: bold; line-height: 1em; }
dd { clear: right; min-height: 1em; margin: 0 0 0 7em; line-height: 1em; }

ul.item-list > li { clear: both; margin-bottom: 0.7em; padding: 0.2em; border: 1px solid #ccc; list-style: none; }

ul.item-list > li:before ,
ul.item-list > li:after { content: ""; display: table; }

ul.item-list > li:after { clear: both; }
ul.item-list > li { zoom: 1; }

</style>
</head>
<body>
	<h1>Public Item</h1>

	<?php
	if (!$this->item) {
		?>
		<p class="note">This item is not available publically.</p>
		<p class="note">Access may be restricted to authorised API users only.</p>
		<?php
	} else {
		$this->render('api_snippets_item.html');
	}
	?>
</body>
</html>