<?php
$lang = $this->model('lang');


$dept = $this->dept;

$this->layout()->addGlobalJavascript();

$this->layout()->appendSection('layout.head', <<<EndJS
<script type="text/javascript">

	$(document).ready(function() {
		var del_button = $('<input type="submit" name="submitdelete" value="Delete Department" />');
		del_button.click(function () {
			return confirm('Please confirm that you want to delete this department.\\n\\nAll items associated with this department will be "orphaned" - we recommend you transfer the items before deleting the department.\\n\\nThis operation cannot be undone.');
		});
		$('#delete_button_container').append(del_button);
	});

</script>
EndJS
);
?>


<?php
Ecl_Helper_Html::form('deptform', $this->request()->uri());
Ecl_Helper_Html::formHidden('session_key', $this->model('user')->getSessionKey());
?>


<input type="submit" name="submitsave" value="Save Changes" style="position: absolute; left: -100%;" />


<div id="delete_button_container"></div>


<h1>Edit <?php $this->out($lang['dept.label']); ?> : <?php $this->out($dept->name); ?></h1>
<p>Here you can edit this <?php $this->out(strtolower($lang['dept.label'])); ?>, or transfer its items to another.</p>


<dl class="form">
	<dt>Name</dt>
	<dd><?php Ecl_Helper_Html::formInput('name', 50, 250, $dept->name); ?></dd>
</dl>

<div>
	<?php Ecl_Helper_Html::formSubmit('submitsave', 'Save Changes'); ?>
</div>



<br />
<h3>Items Listed</h3>
<?php
if (0 < $dept->item_count_internal) {
	?>
	<p>This <?php $this->out(strtolower($lang['dept.label'])); ?> contains <em><?php $this->out($dept->item_count_internal); ?> item<?php echo ((1 < $dept->item_count_internal) ? 's' : ''); ?></em> of equipment.</p>
	<p><a href="<?php echo $this->router()->makeAbsoluteUri("/{$lang['dept.route']}/{$dept->slug}"); ?>">View items in catalogue &raquo;</a></p>
	<?php
	$options = array('' => '') + $this->model('departmentstore')->findAll()->toAssoc('id', 'name');
	unset($options[$dept->id]);

	if (!empty($options)) {
		?>
		<p>If you would like to transfer your items to a different <?php $this->out(strtolower($lang['dept.label'])); ?>, please select a destination to transfer all items to.</p>
		<?php
		Ecl_Helper_Html::formSelect('destination', $options);
		?>
		<br /><br />
		<?php
		$cboxes = array();
		$cboxes[] = array (
			'name'      => 'delete_on_transfer' ,
			'id'        => 'delete_on_transfer' ,
			'label'     => 'Delete current '. strtolower($lang['dept.label']) .' after transfer' ,
			'value'     => '1' ,
			'selected'  => false ,
		);
		Ecl_Helper_Html::formCheckboxTable($cboxes);
		?>
		<br />
		<div>
			<?php Ecl_Helper_Html::formSubmit('submittransfer', 'Transfer Items'); ?>
		</div>
		<?php
	}
} else {
	?>
	<p>This <?php $this->out(strtolower($lang['dept.label'])); ?> contains no items.</p>
	<?php
}
?>



<?php
Ecl_Helper_Html::formClose();
?>


