<div style="margin-bottom: 40px;">
 <h1> Undelete items</h1>
</div>


<div class="">
<form method="post" action="<?php echo $this->router()->makeAbsoluteUri('/admin/undelete/undo') ?>" name="undeleteform" id="undeleteform">
	<?php Ecl_Helper_Html::formHidden('session_key', $this->model('user')->getSessionKey());   ?>
 <table class="table">
  <tr>
  <th>Name</th>
  <th>Owner</th>
  <th>Building</th>
  <th>Undelete</th>
  </tr>
  <?php
  foreach($this->deletedItems as $deletedItem){
  ?>
  <tr>
  <td><?php echo $deletedItem->title ?></td>
  <td><?php echo "{$deletedItem->contact_1_name} ({$deletedItem->contact_1_email})" ?></td>
  <td><?php echo "{$deletedItem->building} ({$deletedItem->room})" ?></td>
  <td><input type="checkbox" name="ids[]" value="<?php echo $deletedItem->id?>"></td>
  </tr>
  <?php } // end foreach loop
    ?>
 </table>
 <div class="pull-right">
<button type="submit" class="btn btn-lg btn-default">Submit</button>
 </div>
 </form>
</div>