<?php
$site = $this->site;


$this->layout()->addGlobalJavascript();

$this->layout()->appendSection('layout.head', '
<script type="text/javascript">

	$(document).ready(function() {

		var del_button = $("<input type=\"submit\" name=\"submitdelete\" value=\"Delete Site\" />");
		del_button.click(function () {
			return confirm("Please confirm that this campus site will be deleted.\n\nAny Items associated with this site will remain, but no longer be registered with the site.\n\nThis operation cannot be undone.");
		});
		$("#delete_button_container").append(del_button);

	});

</script>
');
?>


<h1>Edit Site: <?php $this->out($site->name); ?></h1>

<p>Here you can edit this campus site.</p>

<?php
Ecl_Helper_Html::form('siteform', $this->request()->uri());
Ecl_Helper_Html::formHidden('session_key', $this->model('user')->getSessionKey());
?>

<div class="grid_row">

	<div class="grid_9col">

		<dl>
			<dt>Name</dt>
			<dd><?php Ecl_Helper_Html::formInput('name', 50, 250, $site->name); ?></dd>
		</dl>

		<div style="text-align: center;">
			<?php Ecl_Helper_Html::formSubmit('submitsave', 'Save Changes'); ?>
		</div>

	</div>

	<div class="grid_3col grid_lastcol">

		<div id="delete_button_container"></div>

		<br style="clear: both;" />

		<div class="boxed" style="margin-top: 1em;">
			<p class="title">Items</p>
			<?php
			$items = $this->model('itemstore')->findForSite($site->id, KC__VISIBILITY_INTERNAL);

			if (0 < $items->count()) {
				?>
				<p>This site contains <em><?php $this->out($items->count()); ?> item<?php echo ((1 < $items->count()) ? 's' : ''); ?></em> of equipment.</p>

				<p class="title">Transfer Items</p>
				<?php
				$options = $this->model('sitestore')->findAll()->toAssoc('id', 'name');
				unset($options[$site->id]);

				if (empty($options)) {
					?>
					<p>There are no other sites available.</p>
					<?php
				} else {
					?>
					<p>Select a destination to transfer all items to.</p>
					<?php
					$options = array('' => '') + $options;
					Ecl_Helper_Html::formSelect('destination', $options);
					?>
					<br /><br />
					<?php
					$cboxes = array();
					$cboxes[] = array (
						'name'      => 'delete_on_transfer' ,
						'id'        => 'delete_on_transfer' ,
						'label'     => 'Delete current site after transfer' ,
						'value'     => '1' ,
						'selected'  => false ,
					);
					Ecl_Helper_Html::formCheckboxTable($cboxes);
					?>
					<div style="text-align: right;">
						<?php Ecl_Helper_Html::formSubmit('submittransfer', 'Transfer Items'); ?>
					</div>
					<?php
				}
			} else {
				?>
				<p>This site is not associated with any items.</p>
				<?php
			}
			?>

		</div>

	</div>


</div>

<?php
Ecl_Helper_Html::formClose();
?>