
<h1>Administer Sites</h1>

<div class="cf">


	<div class="admin-box">
		<h3>Add a new site</h3>
		<?php
		Ecl_Helper_Html::form('siteform', $this->router()->makeAbsoluteUri('/admin/sites/create/'));
		Ecl_Helper_Html::formHidden('session_key', $this->model('user')->getSessionKey());
		?>
		<dl class="form">
			<dt><?php Ecl_Helper_Html::formLabel('name', 'Campus/Site Name'); ?></dt>
			<dd><?php Ecl_Helper_Html::formInput('name', 20, 250); ?></dd>
		</dl>

		<?php Ecl_Helper_Html::formSubmit('submitadd', 'Add Site'); ?>

	</div>


	<p>Below is the list of the campus sites available for use in this catalogue.</p>

	<?php
	if ($this->sites->count()==0) {
		?>
		<p class="warning">No sites have been setup yet.</p>
		<?php
	} else {
		?>
		<ul>
			<?php
			foreach($this->sites as $i => $site) {
				$edit_url = $this->router()->makeAbsoluteUri("/admin/sites/edit/{$site->id}");
				printf('<li><a href="%2$s">%1$s%3$s</a></li>', Ecl_Helper_Html::escape($site->name), $edit_url, ( !empty($site->code) ? " &nbsp;({$site->code})" : '' ) );
			}
			?>
		</ul>
		<?php
	}
	?>


</div>


