<?php

function submitbuttons() {
	echo('<div class="reportsubmit">');
	Ecl_Helper_Html::formSubmit('viewreport', 'View');
	Ecl_Helper_Html::formSubmit('downloadreport', 'Download');
	echo('</div>');
}

?>

<div class="page-intro white-box">
	<h1 class="green-bar">Staff Contact Reports</h1>
</div>
<div id="categories" class="white-box">
	<h2>All Staff Contacts</h2>
	<p>Show all the staff contacts defined in the catalogue and the number of items they are responsible for.</p>
	
	<form action="./allstaffcontacts" method="get">
	<?php submitbuttons(); ?>
	</form>
</div>

