<?php
$organisation = $this->organisation;


$this->layout()->addGlobalJavascript();
$this->layout()->appendSection('layout.head', <<<EndJS
<script type="text/javascript">

	$(document).ready(function() {

		var del_button = $('<input type="submit" name="submitdelete" value="Delete Organisation" />');
		del_button.click(function () {
			return confirm('Please confirm that you want to delete this Organisation.\\n\\nThis operation cannot be undone.');
		});
		$('#delete_button_container').append(del_button);

	});

</script>
EndJS
);
?>


<h1>Edit Organisation: <?php $this->out($organisation->name); ?></h1>
<p>Here you can edit this organisation.</p>


<?php
Ecl_Helper_Html::form('organisationform', $this->request()->uri());
Ecl_Helper_Html::formHidden('session_key', $this->model('user')->getSessionKey());
?>


<input type="submit" name="submitsave" value="Save Changes" style="position: absolute; left: -100%;" />


<div id="delete_button_container"></div>


<h3>Organisation details</h3>


<dl class="form">

	<dt>Name</dt>
	<dd><?php Ecl_Helper_Html::formInput('name', 50, 250, $organisation->name); ?></dd>

</dl>

<div>
	<?php Ecl_Helper_Html::formSubmit('submitsave', 'Save Changes'); ?>
</div>


<br />
<h3>Items Listed</h3>
<?php
$items = $this->model('itemstore')->findForOrganisation($organisation->id, KC__VISIBILITY_INTERNAL);

if (0 < $items->count()) {
	?>
	<p>This organisation contains <em><?php $this->out($items->count()); ?> item<?php echo ((1 < $items->count()) ? 's' : ''); ?></em> of equipment.</p>

	<?php
	$options = $this->model('organisationstore')->findAll()->toAssoc('id', 'name');
	unset($options[$organisation->id]);

	if (!empty($options)) {
		?>
		<p>If you would like to transfer your items to a different organisation, please select a destination to transfer all items to.</p>
		<?php
		$options = array('' => '') + $options;
		Ecl_Helper_Html::formSelect('destination', $options);
		?>
		<br /><br />
		<?php
		$cboxes = array();
		$cboxes[] = array (
			'name'      => 'delete_on_transfer' ,
			'id'        => 'delete_on_transfer' ,
			'label'     => 'Delete current organisation after transfer' ,
			'value'     => '1' ,
			'selected'  => false ,
		);
		Ecl_Helper_Html::formCheckboxTable($cboxes);
		?>
		<div style="text-align: right;">
			<?php Ecl_Helper_Html::formSubmit('submittransfer', 'Transfer Items'); ?>
		</div>
		<?php
	}
} else {
	?>
	<p>This organisation is not associated with any items.</p>
	<?php
}



Ecl_Helper_Html::formClose();
?>


