<?php
$block = $this->block;


$this->layout()->addGlobalJavascript();

$this->layout()->appendSection('layout.head', <<<EndJS
<script type="text/javascript">

	$(document).ready(function() {

		var del_button = $('<input type="submit" name="submitdelete" value="Delete Homepage Block" />');
		del_button.click(function () {
			return confirm('Please confirm that you want to delete this homepage block.\\n\\nThis operation cannot be undone.');
		});
		$('#delete_button_container').append(del_button);

	});

</script>
EndJS
);
?>


<?php
Ecl_Helper_Html::form('blockform', $this->request()->uri());
Ecl_Helper_Html::formHidden('session_key', $this->model('user')->getSessionKey());
?>


<input type="submit" name="submitsave" value="Save Changes" style="position: absolute; left: -100%;" />


<div id="delete_button_container"></div>


<h1>Edit Block : <?php $this->out($block->block_name); ?></h1>

<p>Here you can change the name and properties of this block.</p>
<dl class="form">

	<dt>Name</dt>
	<dd><?php Ecl_Helper_Html::formInput('block_name', 50, 250, $block->block_name); ?></dd>

	<dt>Filter on Custom Field</dt>
	<dd><?php Ecl_Helper_Html::formSelect('block_to_find', $this->model('customfieldstore')->findAll()->toAssoc('id', 'name'), $block->block_to_find); ?></dd>

	<dt>Visibility</dt>
	<dd>
		<?php
		$options = array(
			'2' => 'Internal Only' ,
			'1' => 'Public Only' ,
			'3' => 'Both Internal and Public'
		);
		Ecl_Helper_Html::formSelect('visibility', $options, $block->visibility);
		?>
	</dd>

	<dt>Enabled?</dt>
	<dd>
		<?php
		Ecl_Helper_Html::formCheckbox('block_enabled', 'enabled', 'Yes', $block->block_enabled);
		Ecl_Helper_Html::formLabel('enabled', 'Yes, enable this block');
		?>
	</dd>

</dl>

<div>
	<?php Ecl_Helper_Html::formSubmit('submitsave', 'Save Changes'); ?>
</div>



<?php
Ecl_Helper_Html::formClose();
?>


