<?php
$lang = $this->model('lang');


$this->layout()->addBreadcrumb('My Items', $this->router()->makeAbsoluteUri('/myprofile/items/'));


if ($this->model('security')->checkAuth(KC__AUTH_CANADMIN)) {
	$edit_url = $this->router()->makeAbsoluteUri('/admin/items/edit/new');
	$back_url = base64_encode($this->request()->relativeUri());
	printf('<form method="GET"><button class="pull-right btn btn-success" formaction="%1$s">add an item</button><input type="hidden" name="backlink" value="%2$s"></form>', $edit_url, $back_url);
}
?>


<h1>My Items</h1>

<?php
if (0 == count($this->items)) {
	?>
	<p class="note">You have no items associated with your account.</p>
	<?php
} else {
	?>
	<p class="note">The following equipment and facilities are listed against your account.</p>
	<p class="note">If you have editing rights to an item, use the appropriate edit button to amend its details.</p>

	<ul class="item-list">
		<?php
		$url_stub = $this->router()->makeAbsoluteUri("/myprofile/items/");
		foreach($this->items as $item) {
			$this->layout()->renderItemInList($item, "{$url_stub}{$item->idslug}");
		}
		?>
	</ul>
	<?php
}
?>