<?php
$lang = $this->model('lang');


$this->layout()->addBreadcrumb('My Items', $this->router()->makeAbsoluteUri('/myprofile/items/'));


if ($this->model('security')->checkAuth(KC__AUTH_CANADMIN)) {
	$edit_url = $this->router()->makeAbsoluteUri('/admin/items/edit/new');
	$back_url = base64_encode($this->request()->relativeUri());
	printf('<a href="%1$s?backlink=%2$s">add an item &raquo;</a>', $edit_url, $back_url);
}
?>


<h1>My Items</h1>

<?php
if (0 == count($this->items)) {
	?>
	<p class="note">You have no items associated with your email address.</p>
	<?php
} else {
	?>
	<p class="note">The following equipment and facilities are listed against your email address.</p>

	<ul class="item-list">
		<?php
		$url_stub = $this->router()->makeAbsoluteUri("/myprofile/items/");
		foreach($this->items as $item) {
			$this->layout()->renderItemInList($item, "{$url_stub}{$item->url_suffix}");
		}
		?>
	</ul>
	<?php
	}

?>
