<?php
$this->router()->layout(null);
$this->response()->setHeader('Content-Type', 'text/html');
?>
<html>
<head>
<style>

dt { float: left; clear: left; margin: 0 0.5em 0 0; font-weight: bold; line-height: 1em; }
dd { clear: right; min-height: 1em; margin: 0 0 0 7em; line-height: 1em; }

ul.category-list > li { clear: both; margin-bottom: 0.7em; padding: 0.2em; border: 1px solid #ccc; list-style: none; }

ul.category-list > li:before ,
ul.category-list > li:after { content: ""; display: table; }

ul.category-list > li:after { clear: both; }
ul.category-list > li { zoom: 1; }

</style>
</head>
<body>
	<h1>All Public Categories</h1>

	<?php
	if ( 0 == count($this->categories)) {
		?>
		<p class="note">There are no categories available publically.</p>
		<p class="note">Access may be restricted to authorised API users only.</p>
		<?php
	} else {
		$this->render('api_snippets_category_categories.html');
	}
	?>
</body>
</html>