<?php

$user = $this->model('user');
$lang = $this->model('lang');

?>
<h1><?php $this->out($this->model('app.title')); ?></h1>

<?php
if (!Ecl::isEmpty($this->model('app.intro'))) {
	?>
	<p class="note" style="font-size: 1.1em;"><?php echo $this->model('app.intro'); ?></p>
	<?php
}
?>

<ul id="homepage-list" class="cf">
	<li id="browse-categories">
		<h2><a href="<?php echo $this->router()->makeAbsoluteUri("/{$lang['cat.route']}/"); ?>">Browse by <?php $this->out($lang['cat.label']); ?></a></h2>
		<?php
		$categories = $this->model('categorystore')->findUsedRanked(5, $user->param('visibility'));
		if ($categories) {
			?>
			<ul class="item-meta">
				<?php
				$url = $this->router()->makeAbsoluteUri('/browse/'.strtolower($lang['cat.label']). '-');
				foreach($categories as $category) {
					if (false) {
						$url = $this->router()->makeAbsoluteUri("/{$lang['cat.route']}/{$category->slug}");
						$count = $category->getItemCount($user->param('visibility'));
						?>
						<li><a href="<?php echo $url; ?>"><strong><?php $this->out($category->name) ?></strong> <span class="count">(<?php $this->out($count); ?>)</span></a></li>
						<?php
					}
					$count = (!$user->isAnonymous()) ? $category->item_count_internal : $category->item_count_public ;
					?>
					<li><a href="<?php echo "{$url}{$category->id}-".urlencode($category->name); ?>"><strong><?php $this->out($category->name) ?></strong> <span class="count">(<?php $this->out($count); ?>)</span></a></li>
					<?php
				}
				?>
				<li><a href="<?php echo $this->router()->makeAbsoluteUri("/{$lang['cat.route']}/"); ?>">more&hellip;</a></li>
			</ul>
			<?php
		}
		?>
	</li>
	<li id="browse-departments">
		<h2><a href="<?php echo $this->router()->makeAbsoluteUri("/{$lang['dept.route']}/"); ?>">Browse by <?php $this->out($lang['dept.label']); ?></a></h2>
		<?php
		$departments = $this->model('departmentstore')->findUsedRanked(5, $user->param('visibility'));
		if ($departments) {?>
		<ul class="item-meta">
			<?php
			$url = $this->router()->makeAbsoluteUri('/browse/'.strtolower($lang['dept.label']). '-');
			foreach($departments as $department) {
				if (false) {
					$url = $this->router()->makeAbsoluteUri("/{$lang['dept.route']}/{$department->slug}");
					$count = $department->getItemCount($user->param('visibility'));
					?>
					<li><a href="<?php echo $url; ?>"><strong><?php $this->out($department->name) ?></strong> <span class="count">(<?php $this->out($count) ?>)</span></a></li>
					<?php
				}
				$count = (!$user->isAnonymous()) ? $department->item_count_internal : $department->item_count_public ;
				?>
				<li><a href="<?php echo "{$url}{$department->id}-".urlencode($department->name); ?>"><strong><?php $this->out($department->name); ?></strong> <span class="count">(<?php $this->out($count); ?>)</span></a></li>
				<?php
			}
		}
		?>
			<li><a href="<?php echo $this->router()->makeAbsoluteUri("/{$lang['dept.route']}/"); ?>">more&hellip;</a></li>
		</ul>
	</li>


	<?php
	$blocks = $this->model('homepageblockstore')->findAll($user->param('visibility'));
	foreach($blocks as $block) {
		$records = $this->model('customfieldstore')->findUsedCustomFieldValues($block->block_to_find, 5, $user->param('visibility'));
		if (0 < count($records)) {
			$url_stub = $this->router()->makeAbsoluteUri('/customfield/'. urlencode($block->block_to_find_name) .'/'. urlencode($block->block_to_find) .'/');
			?>
			<li class="browse-customfield">
				<h2><a href="<?php echo $url_stub; ?>">Browse by <?php $this->out($block->block_to_find_name); ?></a></h2>
				<ul class="item-meta">
					<?php
					foreach($records as $record) {
						?>
						<li><a href="<?php echo($url_stub . urlencode($record['value']) ); ?>"><strong><?php $this->out(ucwords($record['value'])); ?></strong> <span class="count">(<?php $this->out($record['count']); ?>)</span></a></li>
						<?php
					}
					?>
					<li><a href="<?php echo $url_stub; ?>">more&hellip;</a></li>
				</ul>
			</li>
			<?php
		}
	}
	?>
</ul>


