<?php
$lang = $this->model('lang');

$url_category = urlencode(strtolower($this->category->name));
$this->router()->layout()->addBreadcrumb($this->category->name, $this->router()->makeAbsoluteUri("/{$lang['cat.route']}/{$this->category->slug}"));
$this->router()->layout()->addBreadcrumb($this->item->name, $this->router()->makeAbsoluteUri("/{$lang['cat.route']}/{$this->category->slug}/item/{$this->item->slug}"));


$goto_url = '';
$this->layout()->renderItemInFull($this->item, $goto_url);
?>