<?php
$lang = $this->model('lang');


$this->router()->layout()->addBreadcrumb($this->building->name, $this->router()->makeAbsoluteUri("/{$lang['building.route']}/{$this->building->slug}"));

$back_url = base64_encode($this->request()->relativeUri());
$edit_link = null;

if ($this->model('security')->checkAuth(KC__AUTH_CANADMIN)) {
	$edit_url = $this->router()->makeAbsoluteUri('/admin/items/edit/new');
	$edit_link = sprintf('<form method="GET"><button class="pull-right btn btn-success" formaction="%1$s">add an item</button><input type="hidden" name="backlink" value="%2$s"></form>', $edit_url, $back_url);
}
?>


<h1><?php $this->out($this->category->name); ?></h1>

<?php
echo $edit_link;
if (0 == count($this->items)) {
	?>
	<p class="note">There are no items listed, please try a different <?php $this->out(strtolower($lang['building.label'])); ?>.</p>
	<?php
} else {
	?>
	<p class="note">The following equipment and facilities are listed under this <?php $this->out(strtolower($lang['building.label'])); ?>.</p>

	<ul class="item-list">
		<?php
		$url_stub = $this->router()->makeAbsoluteUri("/{$lang['building.route']}/{$this->building->slug}/item/");
		foreach($this->items as $item) {
			$this->layout()->renderItemInList($item, "{$url_stub}{$item->slug}");
		}
		?>
	</ul>
	<?php
	}

?>
