
<h1>Customise Item Fields</h1>

<p>Using additional fields, you can customise the information you keep on each item of equipment.</p>
<p>Additional fields can be used on any item of equipment in the system, and can be populated using the CSV Import too.</p>


<div class="grid_container">

	<div class="grid_row">

		<div class="grid_8col">
			<?php
			if (empty($this->custom_fields)) {
				?>
				<p class="warning">No custom fields have been setup yet.</p>
				<?php
			} else {
				?>
				<ul>
					<?php
					foreach($this->custom_fields as $field_id => $field_name) {
						echo('<li>'. Ecl_Helper_Html::escape($field_name) .'</li>');
					}
					?>
				</ul>
				<?php
			}
			?>
		</div>

		<div class="grid_4col grid_lastcol">
			<div class="boxed">
				<p class="title">Add a custom field</p>

				<?php
				Ecl_Helper_Html::form('customisationform', $this->router()->makeAbsoluteUri('/admin/items/customise/'));
				Ecl_Helper_Html::formHidden('session_key', $this->model('user')->getSessionKey());
				Ecl_Helper_Html::formInput('name', 30, 100);
				Ecl_Helper_Html::formSubmit('submitadd', 'Add Field');
				Ecl_Helper_Html::formClose();
				?>

			</div>
		</div>

	</div>

</div>
