<?php
?>

<h1>Customise Item Fields</h1>
<p class="note">Using additional fields, you can customise the information you keep on each item of equipment.</p>
<p class="note">Additional fields can be used on any item of equipment in the system, and can be populated using the CSV Import too.</p>

<br />
<?php
if (empty($this->custom_fields)) {
	?>
	<div class="warning">No custom fields have been setup yet.</div>
	<?php
} else {
	?>
	<h4>Existing fields</h4>
	<ul>
	<?php
	foreach($this->custom_fields as $field) {
		echo('<li>'. Ecl_Helper_Html::escape($field->name) .'</li>');
	}
	?>
	</ul>
	<?php
}
?>

<br />
<h4>Add a new custom field</h4>
<?php
Ecl_Helper_Html::form('customisationform', $this->router()->makeAbsoluteUri('/admin/items/customise/'));
Ecl_Helper_Html::formHidden('session_key', $this->model('user')->getSessionKey());
Ecl_Helper_Html::formInput('name', 30, 100);
Ecl_Helper_Html::formSubmit('submitadd', 'Add Field');
Ecl_Helper_Html::formClose();
?>

