<?php
$lang = $this->model('lang');
?>

<h1>Export Items to CSV</h1>
<p>This function will export all your item data to a CSV file.</p>
<p><strong>Please Note</strong> : The exported data cannot be re-imported into your catalogue.  We plan to add this functionality in a future version of Kit-Catalogue.</p>

<div class="item">
	<div>
		<?php
		Ecl_Helper_Html::form('exportform', $this->router()->makeAbsoluteUri('/admin/items/export/?step=2'), 'post', 'UTF-8');
		?>

		<dl>

			<dt><?php Ecl_Helper_Html::formLabel('ou', 'Select which items should be exported');?></dt>
			<dd>
				<select name="ou" id="ou">
					<?php
					$ou_list = $this->model('organisationalunitstore')->findTree();
					foreach($ou_list as $ou) {
						printf('<option value="%1$s" %4$s>%3$s %2$s </option>', $ou->id, $this->escape($ou->name), str_repeat('&nbsp;&nbsp;&nbsp;&nbsp;', $ou->tree_level), ( ($ou->id==$item->ou) ? 'selected="selected"' : null) );
					}
					?>
				</select>
			</dd>

			<dt>Options</dt>
			<dd>
				<?php
				$cboxes = array (
					array (
						'name'      => 'options[]' ,
						'id'        => 'option_includesubtree' ,
						'label'     => "Include items from descended {$lang['ou.label.plural']}." ,
						'value'     => 'include_subtree' ,
						'selected'  => true ,
					),
				);

				Ecl_Helper_Html::formCheckboxTable($cboxes);
				?>
			</dd>

		</dl>

		<div style="margin-top: 2em;">
			<?php
			Ecl_Helper_Html::formSubmit('submitcancel', 'Cancel');
			Ecl_Helper_Html::formSubmit('submitdownload', 'Download');
			?>
		</div>

		<?php Ecl_Helper_Html::formClose(); ?>

	</div>

</div>
