<?php
$this->router()->layout(null);

// IE 8 over HTTPS fix
header("Cache-Control: private, max-age=15");
header("Pragma: ");

header("Content-Description: File Transfer");
header("Content-Disposition: attachment; filename=kitcatalogue_export.csv");
header('Content-Type: text/csv');


$csv_parser = Ecl::factory('Ecl_Parser_Csv');


foreach($this->items as $i => $item) {
	$row = $this->model('itemstore')->convertObjectToExport($item);

	// Output row headers
	if (0 === $i) { echo($csv_parser->generate( array(array_keys($row)))); }

	// Output individual row
	echo($csv_parser->generate(array($row)));
}


