<?php
$this->router()->layout(null);


header("Cache-Control: public");
header("Content-Description: File Transfer");
header("Content-Disposition: attachment; filename=kitcatalogue_export.csv");
header('Content-Type: text/csv');


$csv_parser = Ecl::factory('Ecl_Parser_Csv');


foreach($this->items as $i => $item) {
	$row = $this->model('itemstore')->convertObjectToExport($item);

	// Output row headers
	if (0 === $i) { echo($csv_parser->generate( array(array_keys($row)))); }

	// Output individual row
	echo($csv_parser->generate(array($row) ));
}


