<?php


$lang = $this->model('lang');


$this->layout()->appendSection('layout.head', '
<style type="text/css">

	div.item { border-top: 1px solid #ccc; }

	div.issues { margin-left: 2em; }

	div.issues dt { font-style: normal; font-weight: normal; }

	dl.form dd + dt { margin-top: 1em; }

	dl.form dt { padding: 2px; }
	dl.form dd { margin-left: 0; padding: 1px 2px 3px 1em; }

	.mandatory_error { background-color: #ffe6e6; }

</style>
');
?>


<h1>Import Items from CSV</h1>
<p>Step 3 : Complete the Import</p>
<p>
	The following list of equipment will be added to the catalogue.
	Please examine it carefully before finalising the import.
</p>

<div class="item">

<?php
Ecl_Helper_Html::form('importform', $this->router()->makeAbsoluteUri('/admin/items/import/?step=4'));
Ecl_Helper_Html::formHidden('filename', $this->filename);
Ecl_Helper_Html::formHidden('ignore_rows', $this->ignore_rows);
?>


	<?php
	foreach($this->items as $rownum => $info) {
		$item = $info['item'];
		?>

		<h2 class="import-heading" style="margin-bottom: 0.5em;"><?php $this->out("{$item->name} &nbsp; (row {$rownum})"); ?></h2>
		<?php
		if (!is_array($info['issues'])) {
			?>
			<p style="margin-left: 2em;">All data appears to be OK.</p>
			<?php
		} else {
			?>
			<div class="issues">
				<dl class="form">
				<?php


				uksort($info['issues'], function($a, $b) {
					$sort_order = array (
						'manufacturer'    => 1 ,  // mandatory
						'model'           => 2 ,  // mandatory
						'department'      => 3 ,  // mandatory
						'contact_1_email' => 4 ,  // mandatory

						'technique'       => 5 ,
						'access'          => 6 ,
						'site'            => 7 ,
						'building'        => 8 ,
						'supplier'        => 9 ,
					);

					$a_val = (array_key_exists($a, $sort_order)) ? $sort_order[$a] : 999 ;
					$b_val = (array_key_exists($b, $sort_order)) ? $sort_order[$b] : 999 ;

					if ($a_val == $b_val) { return 0; }
					return ($a_val < $b_val) ? -1 : 1 ;
				});

				foreach($info['issues'] as $k => $v) {

					if (empty($v)) {
						$v = '-- none --';
					}


					// @todo : Allow user to edit the imported value for all issues


					if ('manufacturer' == $k) {
						?>
						<dt class="mandatory_error"><strong>Manufacturer</strong> is mandatory.  You must supply a value for this item below.</dt>
						<dd class="mandatory_error"><?php Ecl_Helper_Html::formInput("manufacturer_{$rownum}", 40, 100, ''); ?></dd>
						<?php
					}


					if ('model' == $k) {
						?>
						<dt class="mandatory_error"><strong>Model</strong> is mandatory.  You must supply a value for this item below.</dt>
						<dd class="mandatory_error"><?php Ecl_Helper_Html::formInput("model_{$rownum}", 40, 100, ''); ?></dd>
						<?php
					}


					if ('contact_1_email' == $k) {
						?>
						<dt class="mandatory_error"><strong><?php echo $lang['item.form.contact_1']; ?></strong> is mandatory.  You must supply a value for this item below.</dt>
						<dd class="mandatory_error">
							<table class="layout">
							<tr>
								<?php
								if ( isset($this->lookups['contact_1_email']) && (!empty($this->lookups['contact_1_email']))) {
									?>
									<td>
										<?php
										Ecl_Helper_Html::formLabel("contact_1_email_{$rownum}", 'Select the '. strtolower($lang['item.form.contact_1']) .' to use');
										?><br />
										<select name="contact_1_email_<?php $this->out($rownum); ?>" id="contact_1_email_<?php $this->out($rownum); ?>">
											<optgroup label="Existing options">
												<?php
												$selected = null;
												$keys = array_keys($this->lookups['contact_1_email']);
												Ecl_Helper_Html::formOptions($this->lookups['contact_1_email'], $selected);
												?>
											</optgroup>
										</select>
									</td>
									<td style="padding-left: 2em;">
										<?php Ecl_Helper_Html::formLabel("new_contact_1_email_{$rownum}", '&hellip; or enter a new '. $lang['item.form.contact_1'] .' email'); ?><br />
										<?php Ecl_Helper_Html::formInput("new_contact_1_email_{$rownum}", 40, 250, ''); ?>
									</td>
									<?php
								} else {
									?>
									<td>
										<?php Ecl_Helper_Html::formLabel("new_contact_1_email_{$rownum}", 'Enter the new '. $lang['item.form.contact_1'] .' email'); ?><br />
										<?php Ecl_Helper_Html::formInput("new_contact_1_email_{$rownum}", 40, 250, ''); ?>
									</td>
									<?php
								}
								?>

							</tr>
							</table>
						</dd>
						<?php
					}


					if ('department' == $k) {
						?>
						<dt class="mandatory_error"><strong><?php echo $lang['dept.label']; ?></strong> is mandatory, but the value imported was not recognised.</dt>
						<dd class="mandatory_error">
							<table class="layout">
							<tr>
								<td>
									<?php Ecl_Helper_Html::formLabel("department_{$rownum}", 'Select the '. strtolower($lang['dept.label']) .' to use'); ?><br />
									<select name="department_<?php $this->out($rownum); ?>" id="department_<?php $this->out($rownum); ?>">
										<?php
										if ($v != '-- none --') {
											?>
											<optgroup label="Imported value">
												<option value="<?php $this->outParam('use_imported'); ?>"><?php $this->out($v); ?></option>
											</optgroup>
											<?php
										}
										?>
										<optgroup label="Existing options">
											<?php
											$selected = null;
											if ( isset($this->lookups['department']) && (!empty($this->lookups['department']))) {
												$keys = array_keys($this->lookups['department']);
												$selected = null;
											}
											Ecl_Helper_Html::formOptions($this->lookups['department'], $selected);
											?>
										</optgroup>
									</select>
								</td>
								<td style="padding-left: 2em; display: none;">
									<?php Ecl_Helper_Html::formLabel("new_department_{$rownum}", '&hellip;or enter a new department name'); ?><br />
									<?php Ecl_Helper_Html::formInput("new_department_{$rownum}", 40, 250, ''); ?>
								</td>
							</tr>
							</table>
						</dd>
						<?php
					}


					if ('access' == $k) {
						?>
						<dt>(optional) <strong>Access Level</strong> not recognised. Confirm the value to use.</dt>
						<dd>
							<select name="access_<?php $this->out($rownum); ?>">
								<optgroup label="Imported value">
									<option value="<?php $this->outParam('use_imported'); ?>" selected="selected"><?php $this->out($v); ?></option>
								</optgroup>
								<optgroup label="Existing options">
									<?php
									$selected = null;
									if ( isset($this->lookups['access']) && (!empty($this->lookups['access']))) {
										$keys = array_keys($this->lookups['access']);
									}
									Ecl_Helper_Html::formOptions($this->lookups['access'], $selected);
									?>
								</optgroup>
							</select>
						</dd>
						<?php
					}


					if ('category' == $k) {
						?>
						<dt>(optional) <strong>Category</strong> not recognised. Confirm the value to use.</dt>
						<dd>
							<select name="category_<?php $this->out($rownum); ?>">
								<optgroup label="Imported value">
									<option value="<?php $this->outParam('use_imported'); ?>" selected="selected"><?php $this->out($v); ?></option>
								</optgroup>
								<optgroup label="Existing options">
									<?php
									$selected = null;
									if ( isset($this->lookups['category']) && (!empty($this->lookups['category']))) {
										$keys = array_keys($this->lookups['category']);
									}
									Ecl_Helper_Html::formOptions($this->lookups['category'], $selected);
									?>
								</optgroup>
							</select>
						</dd>
						<?php
					}


					if ('building' == $k) {
						?>
						<dt>(optional) <strong>Building</strong> not recognised. Confirm the value to use.</dt>
						<dd>
							<select name="building_<?php $this->out($rownum); ?>">
								<optgroup label="Imported value">
									<option value="<?php $this->outParam('use_imported'); ?>" selected="selected"><?php $this->out($v); ?></option>
								</optgroup>
								<optgroup label="Existing options">
									<?php
									$selected = null;
									if ( isset($this->lookups['building']) && (!empty($this->lookups['building']))) {
										$keys = array_keys($this->lookups['building']);
									}
									Ecl_Helper_Html::formOptions($this->lookups['building'], $selected);
									?>
								</optgroup>
							</select>
						</dd>
						<?php
					}


					if ('site' == $k) {
						?>
						<dt>(optional) <strong>Site</strong> not recognised. Confirm the value to use.</dt>
						<dd>
							<select name="site_<?php $this->out($rownum); ?>">
								<optgroup label="Imported value">
									<option value="<?php $this->outParam('use_imported'); ?>" selected="selected"><?php $this->out($v); ?></option>
								</optgroup>
								<optgroup label="Existing options">
									<?php
									$selected = null;
									if ( isset($this->lookups['site']) && (!empty($this->lookups['site']))) {
										$keys = array_keys($this->lookups['site']);
									}
									Ecl_Helper_Html::formOptions($this->lookups['site'], $selected);
									?>
								</optgroup>
							</select>
						</dd>
						<?php
					}


					if ('technique' == $k) {
						/*?>
						<dt><strong>(optional) Technique</strong> not recognised. Confirm the value to use.</dt>
						<dd>
							<select name="technique_<?php $this->out($rownum); ?>">
								<optgroup label="Imported value">
									<option value="<?php $this->outParam('use_imported'); ?>"><?php $this->out($v); ?></option>
								</optgroup>
								<optgroup label="Existing options">
									<?php
									$selected = null;
									if ( isset($this->lookups['technique']) && (!empty($this->lookups['technique']))) {
										$keys = array_keys($this->lookups['technique']);
										$selected = $keys[0];
									}
									Ecl_Helper_Html::formOptions($this->lookups['technique'], $selected);
									?>
								</optgroup>
							</select>
						</dd>
						<?php
						*/
						?>
						<dt>(optional) <strong>Technique</strong> not recognised. Confirm the value to use.</dt>
						<dd><?php Ecl_Helper_Html::formInput("technique_{$rownum}", 50, 250, $item->technique); ?></dd>
					<?php
					}


					if ('supplier' == $k) {
						?>
						<dt>(optional) <strong>Supplier</strong> not recognised. Confirm the value to use.</dt>
						<dd>
							<select name="supplier_<?php $this->out($rownum); ?>">
								<optgroup label="Imported value">
									<option value="<?php $this->outParam('use_imported'); ?>" selected="selected"><?php $this->out($v); ?></option>
								</optgroup>
								<optgroup label="Existing options">
									<?php
									$selected = null;
									if ( isset($this->lookups['supplier']) && (!empty($this->lookups['supplier']))) {
										$keys = array_keys($this->lookups['supplier']);
									}
									Ecl_Helper_Html::formOptions($this->lookups['supplier'], $selected);
									?>
								</optgroup>
							</select>
						</dd>
						<?php
					}


				}
				?>
				</dl>
			</div>
			<?php
		}
	}
	?>


	<div style="text-align: center;">
		<?php
		Ecl_Helper_Html::formSubmit('submitback', '&lt; Back');
		Ecl_Helper_Html::formSubmit('submitcancel', 'Cancel');
		Ecl_Helper_Html::formSubmit('submitfinish', 'Finish');
		?>
	</div>

</div>


<?php Ecl_Helper_Html::formClose(); ?>


