<?php
$lang = $this->model('lang');



if (!empty($this->main_param)) {
	$title = "Browse by {$this->main_param}";
	$first_uri_param = (isset($this->uri_params[$this->main_param])) ? $this->uri_params[$this->main_param] : '' ;
	$this->layout()->addBreadcrumb($title, $this->router()->makeAbsoluteUri("/browse/{$first_uri_param}") );
} else {
	$title = 'Browse Items';
	$this->layout()->addBreadcrumb($title, $this->router()->makeAbsoluteUri('/browse/') );
}



if (2 <= count($this->uri_params)) {
	$this->router()->layout()->addBreadcrumb('Custom filters', $this->router()->makeAbsoluteUri('/browse/') . implode('/', $this->uri_params) );
}



$this->layout()->addGlobalJavascript();
$this->layout()->appendSection('layout.head', <<<EndJS
<script type="text/javascript">

	var clipped_size = '175px';

	$(document).ready( function() {

		$('.clipped-list').each( function(i) {
			var li_list = $(this).find('ul li');
			if (li_list.length > 5) {
				li_list.each( function (idx, el) {
					if (idx>4) { $(el).hide(); }
				});
				$(this).append('<div class="clipped-toggleinfo" data-mode="more" data-target="'+ $(this).attr('id') +'">show all&hellip;</div>');
			}
		});

		$(".clipped-toggleinfo").click(function(event) {
			var target = $('#'+$(this).attr('data-target'));
			var li_list = $(target).find('ul li');

			if ('more' == $(this).attr('data-mode')) {
				if (li_list.length > 5) {
					li_list.each( function (idx, el) {
						if (idx>4) { $(el).show(); }
					});
				}
				$(this).html('show less&hellip;').attr('data-mode', 'less');
			} else {
				if (li_list.length > 5) {
					li_list.each( function (idx, el) {
						if (idx>4) { $(el).hide(); }
					});
				}
				$(this).html('show all&hellip;').attr('data-mode', 'more');
			}
		});

	});


</script>
EndJS
);





if ($this->model('security')->checkAuth(array(KC__AUTH_CANADMIN, KC__AUTH_CANEDIT))) {
	$edit_url = $this->router()->makeAbsoluteUri('/admin/items/edit/new');
	$back_url = base64_encode($this->request()->relativeUri());
	$editlink = sprintf('<a class="admin_link" href="%1$s?backlink=%2$s">add an item</a>', $edit_url, $back_url);
} else {
	$editlink = '';
}


$options = array(
	'category'      => array() ,
	'department'    => array() ,
	'manufacturer'  => array() ,
	'technique'     => array() ,
);

$option_names = array(
	'category'      => $lang['cat.label'] ,
	'department'    => $lang['dept.label'] ,
	'manufacturer'  => $lang['item.label.manufacturer'] ,
	'technique'     => $lang['item.label.technique'] ,
);


// Build the option lists

$category_lookup = $this->model('categorystore')->findAll()->toAssoc('id', 'name');
$department_lookup = $this->model('departmentstore')->findAll()->toAssoc('id', 'name');



// Which options will we be using in the side-bar (i.e. which are not already selected)
$use_category = (!isset($this->selected_params['category']));
$use_department = (!isset($this->selected_params['department']));
$use_manufacturer = (!isset($this->selected_params['manufacturer']));
$use_technique = (!isset($this->selected_params['technique']));



$item_ids = array();



// Build the department, manufacturer and technique option lists (category comes later)
foreach($this->items as $item) {
	$item_ids[] = $item->id;

	if ($use_department) {
		if (isset($options['department'][$item->department])) {
			$options['department'][$item->department]['count']++;
		} else {
			$options['department'][$item->department]['id'] = $item->department;
			$options['department'][$item->department]['name'] = (isset($department_lookup[$item->department])) ? $department_lookup[$item->department] : "Unknown {$lang['dept.label']}" ;
			$options['department'][$item->department]['count'] = 1;
		}
	}

	if ($use_manufacturer) {
		$lcase_id = strtolower($item->manufacturer);

		if (isset($options['manufacturer'][$lcase_id])) {
			$options['manufacturer'][$lcase_id]['count']++;
		} else {
			$options['manufacturer'][$lcase_id]['name'] = (!empty($item->manufacturer)) ? $item->manufacturer : '' ;
			$options['manufacturer'][$lcase_id]['count'] = 1;
		}
	}

	if ($use_technique) {
		$lcase_id = strtolower($item->technique);

		if (isset($options['technique'][$lcase_id])) {
			$options['technique'][$lcase_id]['count']++;
		} else {
			$options['technique'][$lcase_id]['name'] = (!empty($item->technique)) ? $item->technique : '' ;
			$options['technique'][$lcase_id]['count'] = 1;
		}
	}
}



// Build the category option list
if ($use_category) {
	$category_list = $this->model('categorystore')->findCountsForItemCategories($item_ids);

	if (!empty($category_list)) {
		foreach($category_list as $category_id => $count) {
			$options['category'][$category_id]['id'] = $category_id;
			$options['category'][$category_id]['name'] = (isset($category_lookup[$category_id])) ? $category_lookup[$category_id] : "Unknown {$lang['cat.label']}" ;
			$options['category'][$category_id]['count'] = $count;
		}
	}

	$category_list = null;
}


// Sort the currently unsorted options
if (isset($options['manufacturer'])) { ksort($options['manufacturer']); }
if (isset($options['technique'])) { ksort($options['technique']); }




$hide_properties = array();
?>

<h1><?php $this->out($title); ?></h1>

<?php

echo $editlink;


if (!empty($this->selected_params)) {
	?>
	<p>Viewing items matching the following properties:</p>
	<ul class="hozmenu selected-list">
	<?php
	foreach($this->selected_params as $k => $u) {
		$param_key = strtolower($k);

		$uri_params = $this->uri_params;
		unset($uri_params[$param_key]);

		$url = $this->router()->makeAbsoluteUri('/browse/') . implode('/', $uri_params);

		$hide_properties[] = $param_key;

		switch($param_key) {
			case 'category':
				$param_name = $lang['cat.label'];
				$val = (isset($category_lookup[$this->selected_params[$param_key]])) ? $category_lookup[$this->selected_params[$param_key]] : "Unknown {$lang['cat.label']}" ;
				break;
			case 'department':
				$param_name = $lang['dept.label'];
				$val = (isset($department_lookup[$this->selected_params[$param_key]])) ? $department_lookup[$this->selected_params[$param_key]] : "Unknown {$lang['dept.label']}" ;
				break;
			default:
				$param_name = $param_key;
				$val = $this->selected_params[$param_key];
				if (empty($val)) { $val = "-No $k-" ; }
				break;
		}
		?>
		<li><?php $this->out($param_name); ?> : <a href="<?php echo $url; ?>" class="removeparam"><?php $this->out($val); ?> &nbsp;<span class="remove">[x]</span></a></li>
		<?php
	}
	?>
	</ul>
	<?php
}


if (!$this->items) {
	?>
	<p class="note">There are no items of equipment or facilities associated with the properties you selected.</p>
	<?php
}
?>


<div class="side-bar">
	<?php
	$uri = $this->request()->uri();
	if ( (!empty($uri)) && ('/' !== substr($uri, -1)) ) {
		$uri .= '/';
	}


	$css_count = 0;
	foreach($options as $k => $available_options) {
		$css_count++;

		$param_key = strtolower($k);

		if (isset($this->selected_params[$param_key])) {

			$uri_params = $this->uri_params;
			unset($uri_params[$param_key]);

			$url = $this->router()->makeAbsoluteUri('/browse/') . implode('/', $uri_params);

			switch($param_key) {
				case 'category':
					$val = (isset($category_lookup[$this->selected_params[$param_key]])) ? $category_lookup[$this->selected_params[$param_key]] : "Unknown {$lang['cat.label']}" ;
					break;
				case 'department':
					$val = (isset($department_lookup[$this->selected_params[$param_key]])) ? $department_lookup[$this->selected_params[$param_key]] : "Unknown {$lang['dept.label']}" ;
					break;
				default:
					$val = $this->selected_params[$param_key];
					if (empty($val)) { $val = "-No $k-" ; }
					break;
			}
			?>
			<h4><?php $this->out($option_names[$param_key]); ?>&hellip;</h4>
			<div class="clipped-list">
				<ul>
					<li><a href="<?php echo $url; ?>" class="removeparam"><?php $this->out($val); ?> &nbsp;<span class="remove">[x]</span></a></li>
				</ul>
			</div>
			<?php
		} elseif (!empty($available_options)) {
			printf('<h4>%1$s&hellip;</h4>', $this->escape($option_names[$param_key]));

			$url_stub = $uri . strtolower($option_names[$param_key]);
			$option_count = count($available_options);

			$css_id = "clipped-list-{$css_count}";
			?>
			<div class="clipped-list" id="<?php echo $css_id; ?>">

				<ul>
					<?php
					foreach($available_options as $l => $info) {
						$name = (!empty($info['name'])) ? $info['name'] : "-No $k-" ;
						if (isset($info['id'])) {
							$url = $url_stub .'-'. urlencode($info['id']) .'-'. urlencode($info['name']);
						} else {
							$url = $url_stub .'-'. urlencode($info['name']);
						}
						printf('<li><a href="%1$s">%2$s <span class="count">(%3$s)</span></a></li>', $url, $this->escape($name), $info['count']);
					}
					?>
				</ul>
				<?php
				if (false) { //$option_count>3) {
					?>
					<div id="c-<?php echo $css_id; ?>" class="clipped-moreinfo" data-target="<?php echo $css_id; ?>">show all&hellip;</div>
					<?php
				}
				?>
			</div>
			<?php
		}
	}
	?>
</div>


<?php
if ( 0 < count($this->items)) {
	?>
	<ul class="item-list">
		<?php
		$url_stub = "{$uri}item/";
		foreach($this->items as $item) {
			$this->layout()->renderItemInList($item, "{$url_stub}{$item->slug}", $hide_properties);
		}
		?>
	</ul>
	<?php
}
?>


