<?php


if (!empty($this->main_param)) {
	$first_uri_param = (isset($this->uri_params[$this->main_param])) ? $this->uri_params[$this->main_param] : '' ;
	$this->layout()->addBreadcrumb("Browse by {$this->main_param}", $this->router()->makeAbsoluteUri("/browse/{$first_uri_param}") );
} else {
	$this->layout()->addBreadcrumb('Browse Items', $this->router()->makeAbsoluteUri('/browse/') );
}

if (2 <= count($this->uri_params)) {
	$this->layout()->addBreadcrumb('Custom filters', $this->router()->makeAbsoluteUri('/browse/'. implode('/', $this->uri_params)) );
}

$this->layout()->addBreadcrumb($this->item->name, $this->router()->makeAbsoluteUri("/browse/item/{$this->item->slug}"));


$this->layout()->renderItemInFull($this->item);
?>