

<h1>Help</h1>


<div class="dev_todo">
	<p class="title">Sorry, but the support area doesn't contain many resources at the moment.</p>
	<p>A couple of individual help pages are linked to from the appropriate places in the administration system, but until we populate more of the manual, this area will remain pretty empty.</p>
	<p>You should probably click "back", or return to the <a href="<?php echo $this->router()->makeAbsoluteUri('/'); ?>">homepage</a>.</p>
</div>


