<?php
$building = $this->building;


$this->layout()->addGlobalJavascript();

$this->layout()->appendSection('layout.head', <<<EndJS
<script type="text/javascript">

	$(document).ready(function() {

		var del_button = $('<input type="submit" name="submitdelete" value="Delete Building" />');
		del_button.click(function () {
			return confirm('Please confirm that you want to delete this building.\\n\\nThis operation cannot be undone.');
		});
		$('#delete_button_container').append(del_button);

	});

</script>
EndJS
);
?>


<?php
Ecl_Helper_Html::form('buildingform', $this->request()->uri());
Ecl_Helper_Html::formHidden('session_key', $this->model('user')->getSessionKey());
?>


<input type="submit" name="submitsave" value="Save Changes" style="position: absolute; left: -100%;" />


<div id="delete_button_container"></div>


<h1>Edit Building: <?php $this->out($building->name); ?></h1>


<p>Here you can edit this building, or transfer its items to another.</p>
<dl class="form">
	<dt>Building Code</dt>
	<dd><?php Ecl_Helper_Html::formInput('code', 20, 250, $building->code); ?></dd>

	<dt>Name</dt>
	<dd><?php Ecl_Helper_Html::formInput('name', 50, 250, $building->name); ?></dd>

	<dt>Campus Site</dt>
	<dd>
		<?php
		$sites = $this->model('sitestore')->findAll()->toAssoc('id', 'name');

		if (empty($sites)) {
			?>
			<p class="warning">
				No campus sites have been setup yet.
				<br /><br />
				Campus sites are not essential, but we advise taking the time to add them, especially for multi-campus institutions.
			</p>
			<?php
		} else {
			Ecl_Helper_Html::formSelect('site_id', $sites, $building->site_id);
		}
		?>
	</dd>

	<dt><?php Ecl_Helper_Html::formLabel('latitude', 'Latitude'); ?></dt>
	<dd><?php Ecl_Helper_Html::formInput('latitude', 10, 10, $building->latitude); ?></dd>

	<dt><?php Ecl_Helper_Html::formLabel('longitude', 'Longitude'); ?></dt>
	<dd><?php Ecl_Helper_Html::formInput('longitude', 10, 10, $building->longitude); ?></dd>

</dl>

<div>
	<?php Ecl_Helper_Html::formSubmit('submitsave', 'Save Changes'); ?>
</div>

<br />
<h3>Items Listed</h3>
<?php
$items = $this->model('itemstore')->findForBuilding($building->id, KC__VISIBILITY_INTERNAL);

if (0 < $items->count()) {
	?>
	<p>This building contains <em><?php $this->out($items->count()); ?> item<?php echo ((1 < $items->count()) ? 's' : ''); ?></em> of equipment.</p>

	<?php
	/*
	 * @todo : When browse by building is available, uncomment this
	 * <p><a href="<?php echo $this->router()->makeAbsoluteUri("/building/{$building->slug}"); ?>">View items in catalogue</a></p>
	 */
	?>

	<?php
	$options = array('' => '') + $this->model('buildingstore')->findAll()->toAssoc('id', 'name');
	unset($options[$building->id]);

	if (!empty($options)) {
		?>
		<p>If you would like to transfer your items to a different building, please select a destination to transfer all items to.</p>
		<?php
		Ecl_Helper_Html::formSelect('destination', $options);
		?>
		<br /><br />
		<?php
		$cboxes = array();
		$cboxes[] = array (
			'name'      => 'delete_on_transfer' ,
			'id'        => 'delete_on_transfer' ,
			'label'     => 'Delete current department after transfer' ,
			'value'     => '1' ,
			'selected'  => false ,
		);
		Ecl_Helper_Html::formCheckboxTable($cboxes);
		?>
		<div style="text-align: right;">
			<?php Ecl_Helper_Html::formSubmit('submittransfer', 'Transfer Items'); ?>
		</div>
		<?php
	}
} else {
	?>
	<p>This building is not associated with any items.</p>
	<?php
}
?>


<?php
Ecl_Helper_Html::formClose();
?>


