
<h1>Administer Buildings</h1>


<div class="cf">
	<div class="admin-box">
		<h3>Add a new building</h3>
		<?php
		Ecl_Helper_Html::form('buildingform', $this->router()->makeAbsoluteUri('/admin/buildings/create/'));
		Ecl_Helper_Html::formHidden('session_key', $this->model('user')->getSessionKey());
		?>
		<dl class="form">

			<dt><?php Ecl_Helper_Html::formLabel('code', 'Building Code'); ?></dt>
			<dd><?php Ecl_Helper_Html::formInput('code', 10, 10); ?></dd>

			<dt><?php Ecl_Helper_Html::formLabel('name', 'Name'); ?></dt>
			<dd><?php Ecl_Helper_Html::formInput('name', 20, 250); ?></dd>

			<dt><?php Ecl_Helper_Html::formLabel('site_id', 'Campus Site'); ?></dt>
			<dd>
				<?php
				$sites = $this->model('sitestore')->findAll()->toAssoc('id', 'name');

				if (empty($sites)) {
					?>
					<p class="warning">
						No campus sites have been setup yet.
						<br /><br />
						Campus sites are not essential, but we advise taking the time to add them, especially for multi-campus institutions.
					</p>
					<?php
				} else {
					Ecl_Helper_Html::formSelect('site_id', $sites);
				}
				?>
			</dd>

			<dt><?php Ecl_Helper_Html::formLabel('latitude', 'Latitude'); ?></dt>
			<dd><?php Ecl_Helper_Html::formInput('latitude', 10, 10); ?></dd>

			<dt><?php Ecl_Helper_Html::formLabel('longitude', 'Longitude'); ?></dt>
			<dd><?php Ecl_Helper_Html::formInput('longitude', 10, 10); ?></dd>

		</dl>

		<div>
			<?php Ecl_Helper_Html::formSubmit('submitadd', 'Add New Building'); ?>
		</div>

		<?php
		Ecl_Helper_Html::formClose();
		?>
	</div>


	<p>Below is the list of the buildings available for use in this catalogue.</p>

	<?php
	if ($this->buildings->count()==0) {
		?>
		<p class="warning">No buildings have been setup yet.</p>
		<?php
	} else {
		?>
		<ul>
			<?php
			$edit_stub = $this->router()->makeAbsoluteUri('/admin/buildings/edit/');
			foreach($this->buildings as $i => $building) {
				$edit_url = "{$edit_stub}{$building->id}";
				printf('<li><a href="%2$s">%1$s%3$s</a></li>', Ecl_Helper_Html::escape($building->name), $edit_url, ( !empty($building->code) ? " &nbsp;({$building->code})" : '' ) );
			}
			?>
		</ul>
		<?php
	}
	?>

</div>
