<?php
error_reporting(E_ALL);
$www_root = $this->model('app.www');

$lang = $this->model('lang');


?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title><?php echo (!empty($this->_title)) ? "{$this->_title} : " : '' ; ?> <?php echo $this->model('app.title'); ?></title>
	<link href="<?php echo $www_root; ?>/css/style.css" media="all" rel="stylesheet" type="text/css" />
	<link href="<?php echo $www_root; ?>/css/print.css" media="print" rel="stylesheet" type="text/css" />
	<?php
	$this->renderStylesheets();
	$this->renderJavascripts();

	if ($this->model('layout.use_local_css')) {
		?>
	<link href="<?php echo $www_root; ?>/local/css/local.css" media="all" rel="stylesheet" type="text/css" />
		<?php
	}
	$this->renderSection('layout.head');
	?>
</head>
<?php echo $this->getSection('layout.pre-body'); ?>
<body>

<div id="wrapper">

	<div id="header">
		<div class="header-wrapper">
			<a class="logo" href="/"><img src="<?php echo $www_root; ?>/images/logo-kc.jpg" alt="Kit-Catalogue" /></a>

			<?php
		$org_logo = $this->model()->get('org.logo');
		if (!empty($org_logo)) {
			?>
			<a class="logo institution" href="#"><img src="<?php echo $www_root; ?>/local/images/<?php echo $org_logo; ?>" alt="<?php echo $this->model('org.title'); ?>" /></a>
			<?php
		}
		$this->renderSection('layout.header');

		$user = $this->model('user');
		?>
		</div>
	</div>


	<?php
	if (!$user->isAnonymous()) {
		?>
	<div id="userbar" class="cf">
		<ul id="usernav">
			<li><a href="<?php echo $www_root; ?>/signin/signout">Sign Out</a></li>
			<?php
			if ($this->model('security')->checkAuth(KC__AUTH_CANADMIN)) {
				?>
				<li><a href="<?php echo $www_root; ?>/admin">Administration</a></li>
				<?php
			}
			?>
			<li>Welcome <strong><?php $this->out("{$user->forename} {$user->surname}"); ?></strong></li>
		</ul>
	</div>
		<?php
	}
	?>

	<div id="top">
		<ul id="nav" class="cf">
			<li><a href="<?php echo $www_root; ?>/">Home</a></li>
			<?php
			if ( !$this->model('user')->isAnonymous() || $this->model('app.allow_anonymous') ) {
			?>
			<li><a href="<?php echo $www_root; ?>/category/"><?php $this->out($lang['cat.label.plural']); ?></a></li>
			<li><a href="<?php echo $www_root; ?>/<?php echo $lang['dept.route'] ?>/"><?php $this->out($lang['dept.label.plural']); ?></a></li>
			<li><a href="<?php echo $www_root; ?>/item/">Items A - Z</a></li>
			<?php
			}
			if ($user->isAnonymous()) {
				?>
				<li class="user" style="float: right;"><a href="<?php echo $www_root; ?>/signin/">Sign In</a></li>
				<?php
			}
			?>
		</ul>
		<?php
		if ($this->hasBreadcrumbs()) {?>
		<ul id="breadcrumbs"><?php
			$this->renderBreadcrumbs();?>
		</ul><?php
		}
		if ( (!$this->model('user')->isAnonymous()) || ($this->model('app.allow_anonymous')) ) {?>
		<form id="search-form" action="<?php echo $www_root; ?>/search/" method="get">
			<div id="search-box">
				<input type="text" name="q" id="search" class="hint" value="Search..." onfocus="if (this.value=='Search...') { this.className = ''; this.value = ''; }" onblur="if (this.value == '') { this.className = 'hint'; this.value = 'Search...'; }" />
				<input type="image" name="searchsubmit" id="search-image" src="<?php echo $www_root; ?>/images/bg-search.png" />
			</div>
		</form><?php
		}

		if ($this->model('user')->isAnonymous()) {
			?>
			<p class="signin_warning"><strong>Please <a href="<?php echo $this->router()->makeAbsoluteUri("/signin/"); ?>" style="font-weight: bold;">sign in</a> to view the full catalogue.</strong> Only some items of equipment may be visible to the public.</p>
			<?php
		}
		?>
	</div>
	<?php
	$this->renderFeedback();

	$this->renderSection('layout.pre-content');

	echo $this->content();

	$this->renderSection('layout.post-content');
	?>
	<div id="footer">

		<?php $this->renderSection('layout.footer'); ?>

		<p><a class="link" href="mailto:<?php $this->out($this->model('app.email')); ?>">Contact the catalogue owner</a></p>

		<p>This equipment database is powered by the <a href="http://www.kit-catalogue.com/">Kit-Catalogue</a> system (v.<?php $this->out($this->model('app.version')); ?>).<br />
		Kit-Catalogue has been developed by Loughborough University and is licensed under the <a href="http://www.gnu.org/copyleft/gpl.html">Open Source GPLv3 licence</a>.</p>
	</div>
</div>

<?php $this->renderSection('layout.post-body'); ?>

<iframe src="<?php echo $www_root; ?>/keep_alive.php" height="1" width="1" style="display: none;">keep alive</iframe>

</body>
</html>