<?php
$item = $this->item;
$form = $this->form;

$back_url = base64_encode($this->backlink);

$this->layout()->addBreadcrumb('Item', $this->router()->makeAbsoluteUri($this->backlink));
$this->layout()->addBreadcrumb('Item Enquiry', $this->router()->makeAbsoluteUri("/enquiry/{$item->id}?backlink={$back_url}"));
?>


<h2>Item Enquiry</h2>
<p class="note">Complete the form below to enquire about this equipment.  A copy of your enquiry will be emailed to you.</p>
<p class="note">* denotes a required field.</p>

<?php
Ecl_Helper_Html::form('enquiryform', $this->router()->makeAbsoluteUri("/enquiry/{$item->id}?backlink={$back_url}"), 'post', 'UTF-8', 'class="form-horizontal"');
?>

<div class="form">
<input type="submit" name="submitfake" value="fake" onclick="return false;" style="position: absolute; left: -100%;" />

<fieldset>
	<legend>Equipment Information</legend>
	<table class="fields" style="margin-left: 2em;">
	<tr>
		<th>Name</th>
		<td><?php $this->out($item->name); ?></td>
	</tr>
	<tr>
		<th>Location</th>
		<td><?php $this->out($this->model('organisationalunitstore')->lookupName($item->ou)); ?></td>
	</tr>
	<?php
	if (!empty($item->access)) {
		?>
		<tr>
			<th>Access Level</th>
			<td><?php $this->out($this->model('accesslevelstore')->lookupName($item->access)); ?></td>
		</tr>
		<?php
	}
	?>
	</table>
</fieldset>

<fieldset>
     <div class="form-group">
     <?php Ecl_Helper_Html::formLabel('name', 'Name *', array('class' => "col-sm-3 control-label")); ?>
    <div class="col-sm-9">
      <?php Ecl_Helper_Html::formInput('name', 30, 250, $form['name'], array('class'=>'form-control')); ?>  
      <p class="help-block">Your full name.</p>
    </div>
  </div>
  <div class="form-group">
     <?php Ecl_Helper_Html::formLabel('email', 'Email *', array('class' => "col-sm-3 control-label")); ?>
    <div class="col-sm-9">
      <?php Ecl_Helper_Html::formInput('email', 40, 250, $form['email'], array('class'=>'form-control')); ?>  
      <p class="help-block">Your contact email address - your enquiry receipt will be sent here.</p>
    </div>
  </div>
  <div class="form-group">
     <?php Ecl_Helper_Html::formLabel('role', 'Role / Job Title', array('class' => "col-sm-3 control-label")); ?>
    <div class="col-sm-9">
      <?php Ecl_Helper_Html::formInput('role', 40, 250, $form['role'], array('class'=>'form-control')); ?>  
      <p class="help-block">Are you an academic, PhD student, undergraduate student, etc?</p>
    </div>
  </div>
  <div class="form-group">
     <?php Ecl_Helper_Html::formLabel('org', 'Organisation / Institution', array('class' => "col-sm-3 control-label")); ?>
    <div class="col-sm-9">
      <?php Ecl_Helper_Html::formInput('org', 40, 250, $form['org'], array('class'=>'form-control')); ?>  
      <p class="help-block">Your university or company name.</p>
    </div>
  </div>
   <div class="form-group">
     <?php Ecl_Helper_Html::formLabel('phone', 'Phone Number', array('class' => "col-sm-3 control-label")); ?>
    <div class="col-sm-9">
      <?php Ecl_Helper_Html::formInput('phone', 20, 20, $form['phone'], array('class'=>'form-control')); ?>  
      <p class="help-block">Your contact telephone number.</p>
    </div>
  </div>
  <div class="form-group">
     <?php Ecl_Helper_Html::formLabel('deadline', 'Booking Deadline', array('class' => "col-sm-3 control-label")); ?>
    <div class="col-sm-9">
      <?php Ecl_Helper_Html::formInput('deadline', 40, 50, $form['deadline'], array('class'=>'form-control')); ?>  
      <p class="help-block">If requesting an equipment booking, when must the work be completed?</p>
    </div>
  </div>
  <div class="form-group">
     <?php Ecl_Helper_Html::formLabel('type', 'Type', array('class' => "col-sm-3 control-label")); ?>
    <div class="col-sm-9">
      	<?php
			$options = array(
				'general'   => 'General enquiry' ,
				'booking'   => 'Booking request' ,
				'research'  => 'Research collaboration' ,
			);
			Ecl_Helper_Html::formSelect('type', $options, $form['type'], array('class'=>'form-control'));
			?>
    </div>
  </div>
   <div class="form-group">
     <?php Ecl_Helper_Html::formLabel('body', 'Enquiry Text *', array('class' => "col-sm-3 control-label")); ?>
    <div class="col-sm-9">
      	<?php Ecl_Helper_Html::formTextarea('body', 80, 6, $form['body'], array('class'=>'form-control')); ?>  
      <p class="help-block">Enter the text for your enquiry, including any relevant information not entered elsewhere.</p>
    </div>
  </div>
   
	<legend>Your Details</legend>

</fieldset>

<?php
if ( $this->model('enquiry.use_recaptcha') && (!Ecl::isEmpty($this->model('recaptcha.public_key'))) && (!Ecl::isEmpty($this->model('recaptcha.private_key'))) ) {
	$recaptcha_error = $this->recaptcha_error;
	?>
	<fieldset>

		<dl class="form">

			<dt>Please enter the two words shown in the image below.</dt>
			<dd>
				<?php
				$use_ssl = (strpos($this->router()->makeAbsoluteUri('/'), 'https')===0);
				require_once($this->model('app.include_root').'/library/recaptcha/recaptchalib.php');
				echo recaptcha_get_html($this->model('recaptcha.public_key'), $recaptcha_error, $use_ssl);
				?>
			<dd>

		</dl>
	</fieldset>
	<?php
}
?>

<div class="button_bar">
	<?php Ecl_Helper_Html::formSubmit('submitcancel', 'Cancel', array('class' => "btn btn-danger")); ?>
	<?php Ecl_Helper_Html::formSubmit('submitsend', 'Send Enquiry', array('class' => "btn btn-success")); ?>
</div>

<?php
Ecl_Helper_Html::formClose();
?>
</div>
