<?php
$item = $this->item;
$form = $this->form;

$back_url = base64_encode($this->backlink);

$this->layout()->addBreadcrumb('Item', $this->router()->makeAbsoluteUri($this->backlink));
$this->layout()->addBreadcrumb('Item Enquiry', $this->router()->makeAbsoluteUri("/enquiry/{$item->id}?backlink={$back_url}"));
?>


<h1>Item Enquiry</h1>
<p class="note">Complete the form below to enquire about this equipment.  A copy of your enquiry will be emailed to you.</p>
<p class="note">* denotes a required field.</p>

<?php
Ecl_Helper_Html::form('enquiryform', $this->router()->makeAbsoluteUri("/enquiry/{$item->id}?backlink={$back_url}"));
?>


<input type="submit" name="submitfake" value="fake" onclick="return false;" style="position: absolute; left: -100%;" />

<fieldset>
	<legend>Equipment Information</legend>
	<table class="fields" style="margin-left: 2em;">
	<tr>
		<th>Name</th>
		<td><?php $this->out($item->name); ?></td>
	</tr>
	<tr>
		<th>Department</th>
		<td><?php $this->out($this->model('departmentstore')->lookupName($item->department)); ?></td>
	</tr>
	<?php
	if (!empty($item->access)) {
		?>
		<tr>
			<th>Access Level</th>
			<td><?php $this->out($this->model('accesslevelstore')->lookupName($item->access)); ?></td>
		</tr>
		<?php
	}
	?>
	</table>
</fieldset>

<fieldset>
	<legend>Your Details</legend>
	<table class="layout">
	<tr>
		<td>
			<dl class="form" style="margin-left: 2em;">

				<dt><?php Ecl_Helper_Html::formLabel('name', 'Name *'); ?></dt>
				<dd>
					<p class="note">Your full name.</p>
					<?php Ecl_Helper_Html::formInput('name', 30, 250, $form['name']); ?>
				</dd>

				<dt><?php Ecl_Helper_Html::formLabel('email', 'Email *'); ?></dt>
				<dd>
					<p class="note">Your contact email address - your enquiry receipt will be sent here.</p>
					<?php Ecl_Helper_Html::formInput('email', 40, 250, $form['email']); ?>
				</dd>

				<dt><?php Ecl_Helper_Html::formLabel('phone', 'Phone Number'); ?></dt>
				<dd>
					<p class="note">Your contact telephone number.</p>
					<?php Ecl_Helper_Html::formInput('phone', 20, 20, $form['phone']); ?>
				</dd>

			</dl>
		</td>
		<td>
			<dl class="form" style="margin-left: 5em;">

				<dt><?php Ecl_Helper_Html::formLabel('org', 'Organisation / Institution'); ?></dt>
				<dd>
					<p class="note">Your university or company name.</p>
					<?php Ecl_Helper_Html::formInput('org', 40, 250, $form['org']); ?>
				</dd>

				<dt><?php Ecl_Helper_Html::formLabel('role', 'Role / Job Title'); ?></dt>
				<dd>
					<p class="note">Are you an academic, PhD student, undergraduate student, etc?</p>
					<?php Ecl_Helper_Html::formInput('role', 40, 250, $form['role']); ?>
				</dd>

				<dt><?php Ecl_Helper_Html::formLabel('deadline', 'Booking Deadline'); ?></dt>
				<dd>
					<p class="note">If requesting an equipment booking, when must the work be completed?</p>
					<?php Ecl_Helper_Html::formInput('deadline', 40, 50, $form['deadline']); ?>
				</dd>

			</dl>
		</td>
	</tr>
	</table>
</fieldset>

<fieldset>
	<legend>Your Enquiry</legend>
	<dl class="form" style="margin-left: 2em;">

		<dt><?php Ecl_Helper_Html::formLabel('type', 'Type'); ?></dt>
		<dd>
			<?php
			$options = array(
				'general'   => 'General enquiry' ,
				'booking'   => 'Booking request' ,
				'research'  => 'Research collaboration' ,
			);
			Ecl_Helper_Html::formSelect('type', $options, $form['type']);
			?>
		</dd>

		<dt><?php Ecl_Helper_Html::formLabel('body', 'Text *'); ?></dt>
		<dd>
			<p class="note">Enter the text for your enquiry, including any relevant information not entered elsewhere.</p>
			<?php Ecl_Helper_Html::formTextarea('body', 80, 6, $form['body']); ?>
		</dd>

	</dl>

</fieldset>

<?php
if ( $this->model('enquiry.use_recaptcha') && (!Ecl::isEmpty($this->model('recaptcha.public_key'))) && (!Ecl::isEmpty($this->model('recaptcha.private_key'))) ) {
	$recaptcha_error = $this->recaptcha_error;
	?>
	<fieldset>

		<dl class="form">

			<dt>Please enter the two words shown in the image below.</dt>
			<dd>
				<?php
				$use_ssl = (strpos($this->router()->makeAbsoluteUri('/'), 'https')===0);
				require_once($this->model('app.include_root').'/library/recaptcha/recaptchalib.php');
				echo recaptcha_get_html($this->model('recaptcha.public_key'), $recaptcha_error, $use_ssl);
				?>
			<dd>

		</dl>
	</fieldset>
	<?php
}
?>

<div class="button_bar">
	<?php Ecl_Helper_Html::formSubmit('submitcancel', 'Cancel'); ?>
	<?php Ecl_Helper_Html::formSubmit('submitsend', 'Send Enquiry'); ?>
</div>

<?php
Ecl_Helper_Html::formClose();
?>

