<?php



$www_root = $this->model('app.www');



$this->layout()->appendSection('layout.head', '
	<!-- INSTALL.REWRITE=OK (This string is checked for as part of the installation process) -->
	<style type="text/css">

		#signonform { margin-bottom: 1em; }

	</style>
	<script type="text/javascript">

		window.onload = function() {
			var uname = document.getElementById("username");
			uname.focus();
		}

	</script>
');


$this->layout()->addBreadcrumb('Sign In', $this->router()->makeAbsoluteUri('/signin/'));



switch (strtolower($this->request()->get('msg'))) {
	case 'failed':
		$this->layout()->addFeedback(KC__FEEDBACK_ERROR , 'Your username and password were rejected.' ,	'Please check your username and password and try again.');
		break;
	case 'signedout':
		$this->layout()->addFeedback(KC__FEEDBACK_SUCCESS ,	'You have signed out.');
		break;
	case 'notsupported':
		$this->layout()->addFeedback(KC__FEEDBACK_ERROR, 'The authentication method selected is not supported.', 'Please use another sign-in option and try again.');
		break;
	default:
		break;
}



?>
<div class="container" style="text-align: center; margin-bottom: 40px;">
<h2>Sign in to <?php $this->out($this->model('app.title')); ?>.</h2>
</div>
<?php
$use_https = $this->model('app.use_https') ? true : false ;
?>
<form action="<?php echo $this->router()->makeAbsoluteUri('/signin/check/', $use_https); ?>" method="post" id="signonform">

<div class="form-horizontal" style="max-width: 330px; margin: 0 auto;">

   <div class="form-group">
     <?php Ecl_Helper_Html::formLabel('username', 'Username', array('class' => "col-sm-4 control-label")); ?>
    <div class="col-sm-8">
      <?php Ecl_Helper_Html::formInput('username', '12', '50','', array('class'=>'form-control')); ?>  
    
    </div>
  </div>
  <div class="form-group">
    <?php Ecl_Helper_Html::formLabel('password', 'Password', array('class' => "col-sm-4 control-label")); ?>
    <div class="col-sm-8">
      <?php Ecl_Helper_Html::formPassword('password', '12', '50','', array('class'=>'form-control')); ?>  
      
    </div>
  </div>


	    <div class="button_bar">
        <?php Ecl_Helper_Html::formSubmit('signin', 'Sign in', array('class' => "btn btn-lg btn-primary btn-block")); ?>
     </div>
			
</div>

<?php
if ($this->model('signin.use_shibboleth')) {
	?>
	<div class="sso-box">
		<p>Click the link to access using Single Sign-On.</p>
		<div><a class="sso-link" href="/sso/">Use Single Sign-On</a></div>
	</div>
	<?php
}
?>

</form>
<br />
<br />

<h3 style="text-align: center; margin-bottom: 40px;">Signing in allows you to..</h3>
<ul style="margin: 0 auto; max-width: 330px; list-style: disc;">
	<li>Browse and search the full equipment database.</li>
	<li>Check an item's location.</li>
	<li>Access manuals, case studies and other supporting documentation.</li>
</ul>


